# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('push_path', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32)),
                ('p_cname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=32)),
                ('pl_cname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PushTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=32)),
                ('target_cname', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='productionline',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.PushTarget'),
        ),
        migrations.AddField(
            model_name='production',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ProductionLine'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Production'),
        ),
    ]
